
services:
  app:
    image: crisywini/wardrobe-wizard-api:v1.1.1
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/wardrobe_db
    volumes:
      - .:/src
      - ./images:/app/images
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend: 
    image: crisywini/the-wardrobe-grimmerie:v1.1.0
    ports:
      - "8080:80"
    depends_on:
      - app


volumes:
  mongo_data:
